apiVersion: v1alpha
kind: playwright
sauce:
  region: us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.ts # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  - name: "Firefox Win"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ['tests/ui/*.*.ts']
    params:
      browserName: "firefox"
      project: "firefox"  # Runs the project that's defined in `playwright.config.js`
  - name: "Chromium Mac"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/ui/*.*.ts']
    params:
      browserName: "chromium"
      project: "chromium"
  - name: "Webkit Win"
    platformName: "Windows 11"
    screenResolution: "1440x900"
    testMatch: ['tests/ui/*.*.ts']
    params:
      browserName: "webkit"
      project: "webkit"
# Controls what artifacts to fetch when the suites have finished.
# artifacts:
#   download:
#     when: always
#     match:
#       - console.log
#     directory: ./artifacts/
npm:
  registry: https://registry.npmjs.org
  packages:
    "@cucumber/cucumber": "^9.1.2"
    "@playwright/test": "^1.34.3"
    "@reportportal/agent-js-playwright": "^5.1.2"
    "@types/jest": "^29.5.0"
    "@typescript-eslint/eslint-plugin": "^5.59.0"
    "@wdio/allure-reporter": "^8.11.0"
    "@wdio/cli": "^8.11.2"
    "@wdio/local-runner": "^8.11.2"
    "@wdio/mocha-framework": "^8.11.0"
    "@wdio/spec-reporter": "^8.11.2"
    "allure-playwright": "^2.1.0"
    "chai": "^4.3.7"
    "chromedriver": "^114.0.2"
    "cross-env": "^7.0.3"
    "dotenv": "^16.0.3"
    "eslint-config-prettier": "^8.8.0"
    "eslint-plugin-prettier": "^4.2.1"
    "husky": "^8.0.3"
    "jest": "^29.5.0"
    "jest-junit-reporter": "^1.1.0"
    "jest-playwright-preset": "^3.0.1"
    "json-query": "^2.2.2"
    "lint-staged": "^13.2.1"
    "mocha": "^10.2.0"
    "monocart-reporter": "^1.6.12"
    "pactum": "^3.3.3"
    "playwright": "^1.32.3"
    "prettier": "2.8.7"
    "sonarqube-scanner": "^3.0.1"
    "ts-jest": "^29.1.0"
    "ts-node": "^10.9.1"
    "typescript": "^5.1.3"
    "wdio-chromedriver-service": "^8.1.1"
    "winston": "^3.8.2"
    "@delta-reporter/wdio-delta-reporter-service": "^1.1.10"

  env:
    env_var: remote
